"""empty message

Revision ID: c933ea0b706e
Revises: 60b98a9de4b3
Create Date: 2020-03-20 20:41:57.010670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c933ea0b706e'
down_revision = '60b98a9de4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created')
    op.drop_column('Artist', 'created')
    # ### end Alembic commands ###
